language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
# command to run tests
script:
  - cd bl
  - coverage run --source='api' ./manage.py test && coverage report
after_success:
  coveralls
