# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171116_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
